version: 2

models:
  - name: stg_campaigns_data  
    description: "Modèle transformant les données des campagnes marketing en filtrant les lignes sans canal et nettoyant les colonnes."
    columns:
      - name: id_campagne
        description: "Identifiant unique de la campagne marketing."
        tests:
          - not_null
          - unique
      - name: date
        description: "Date associée à la campagne."
        tests:
          - not_null
      - name: événement_oui_non
        description: "Indicateur pour les événements Oui/Non (statique pour cet exemple)."
      - name: événement_type
        description: "Type d'événement associé (statique pour cet exemple)."
      - name: canal
        description: "Canal marketing utilisé pour la campagne (e.g., Email, Social Media)."
        tests:
          - not_null
      - name: budget
        description: "Budget alloué à la campagne marketing."
        tests:
          - not_null
          - accepted_values:
              values: [">=0"]  # Valider que le budget est supérieur ou égal à 0
      - name: clics
        description: "Nombre de clics enregistrés pour la campagne."
        tests:
          - not_null
          - accepted_values:
              values: [">=0"]  # Valider que les clics ne sont pas négatifs
      - name: CTR
        description: "Taux de clics (Click-Through Rate) calculé pour la campagne."
        tests:
          - not_null
          - accepted_values:
              values: [">=0"]  # Valider que le CTR n'est pas négatif



  - name: stg_produits
    description: "Modèle des produits avec leurs catégories, marques, prix, etc."
    columns:
      - name: ID
        description: "Identifiant unique du produit"
        tests:
          - not_null
          - unique
      - name: Catégorie
        description: "Catégorie du produit"
        tests:
          - not_null
      - name: Marque
        description: "Marque du produit"
        tests:
          - not_null
      - name: Produit
        description: "Nom du produit"
        tests:
          - not_null
      - name: Prix
        description: "Prix du produit"
        tests:
          - not_null
          - accepted_values:
              values: [ "prix_min", "prix_max" ]  # Ajustez avec des valeurs spécifiques si nécessaire
      - name: Souscatégorie
        description: "Sous-catégorie du produit"
        tests:
          - not_null
      - name: Variation
        description: "Variation du produit (ex: couleur, taille, etc.)"
        tests:
          - not_null

  - name: stg_commandes_data
    description: |
      Modèle de staging qui nettoie et transforme les données des commandes des clients.
    columns:
      - name: id_commande
        description: "Identifiant unique de la commande"
        tests:
          - unique
          - not_null
      - name: id_client
        description: "Identifiant unique du client ayant passé la commande"
        tests:
          - not_null
      - name: id_entrepôt_départ
        description: "Identifiant de l'entrepôt d'où la commande a été expédiée"
      - name: date_commande
        description: "Date à laquelle la commande a été passée"
        tests:
          - not_null
      - name: statut_commande
        description: "Statut actuel de la commande (ex. En cours, Expédiée, Livrée)"
        tests:
          - not_null
      - name: id_promotion_appliquée
        description: "Identifiant de la promotion appliquée à la commande, le cas échéant"
      - name: mode_de_paiement
        description: "Mode de paiement choisi par le client (ex. Carte de crédit, PayPal)"
        tests:
          - not_null
      - name: numéro_tracking
        description: "Numéro de suivi de la commande pour la livraison"
      - name: date_livraison_estimée
        description: "Date estimée de livraison de la commande"
        tests:
          - not_null

  - name: stg_satisfaction_data
    description: |
      Modèle de staging qui nettoie et transforme les données de satisfaction des clients.
    columns:
      - name: id_satisfaction
        description: "Identifiant unique de l'enquête de satisfaction"
        tests:
          - unique
          - not_null
      - name: id_commande
        description: "Identifiant de la commande associée à la satisfaction"
        tests:
          - not_null
      - name: note_client
        description: "Note attribuée par le client (ex. de 1 à 5)"
        tests:
          - not_null
      - name: commentaire
        description: "Commentaire du client sur la commande"
      - name: plainte
        description: "Indication de la présence d'une plainte du client (ex. Oui/Non)"
      - name: temps_réponse_support
        description: "Temps de réponse du support client après une plainte"
      - name: type_plainte
        description: "Type de plainte formulée par le client (ex. Produit défectueux, Livraison en retard)"
      - name: employé_support
        description: "Nom ou identifiant de l'employé du support ayant pris en charge la plainte"

  - name: stg_posts_data
    description: |
      Modèle de staging qui nettoie et transforme les données des posts sur les réseaux sociaux.
    columns:
      - name: id_post
        description: "Identifiant unique du post"
        tests:
          - unique
          - not_null
      - name: date_post
        description: "Date à laquelle le post a été publié"
        tests:
          - not_null
      - name: canal_social
        description: "Plateforme de réseau social où le post a été publié (ex. Facebook, Instagram, Twitter)"
        tests:
          - not_null
      - name: volume_mentions
        description: "Volume total de mentions ou d'interactions générées par ce post"
      - name: sentiment_global
        description: "Sentiment général du post (positif, neutre, négatif)"
      - name: contenu_post
        description: "Contenu textuel ou description du post"

  - name: stg_entrepots_data
    description: |
      Modèle de staging qui nettoie et transforme les données des entrepôts.
    columns:
      - name: id_entrepôt
        description: "Identifiant unique de l'entrepôt"
        tests:
          - unique
          - not_null
      - name: localisation
        description: "Localisation géographique de l'entrepôt"
        tests:
          - not_null
      - name: capacité_max
        description: "Capacité maximale de stockage de l'entrepôt"
      - name: volume_stocké
        description: "Volume actuel stocké dans l'entrepôt"
      - name: taux_remplissage
        description: "Taux de remplissage actuel de l'entrepôt"
      - name: température_moyenne_entrepôt
        description: "Température moyenne au sein de l'entrepôt"

  - name: stg_machines_data
    description: |
      Modèle de staging qui nettoie et transforme les données des machines des entrepôts.
    columns:
      - name: id
        description: "Identifiant unique pour chaque machine"
        tests:
          - unique
          - not_null
      - name: id_machine
        description: "Identifiant unique de la machine"
        tests:
          - not_null
      - name: id_entrepôt
        description: "Identifiant de l'entrepôt auquel la machine est associée"
      - name: type_machine
        description: "Type de la machine (ex. Machine de tri, Machine de stockage)"
      - name: état_machine
        description: "État de la machine (ex. Fonctionnelle, En panne)"
      - name: temps_darrêt
        description: "Temps d'arrêt de la machine en heures"
      - name: volume_traité
        description: "Volume de produits traités par la machine"
      - name: mois
        description: "Mois pour lequel les données sont collectées"

  - name: stg_details_commandes_data
    description: |
      Modèle de staging qui nettoie et transforme les détails des commandes.
    columns:
      - name: id_commande
        description: "Identifiant unique de la commande"
        tests:
          - not_null
      - name: id_produit
        description: "Identifiant unique du produit"
        tests:
          - not_null
      - name: quantité
        description: "Quantité de produit dans la commande"
      - name: emballage_spécial
        description: "Indication si un emballage spécial a été demandé pour la commande"

  - name: stg_clients_data
    description: |
      Modèle de staging qui nettoie et transforme les données des produits favoris des clients.
    columns:
      - name: id_client
        description: "Identifiant unique du client"
        tests:
          - not_null
      - name: prenom_client
        description: "Prénom du client"
      - name: nom_client
        description: "Nom du client"
      - name: âge
        description: "Âge du client"
      - name: id_produit_favori
        description: "Identifiant unique du produit favori"
        tests:
          - not_null

  - name: stg_produits
    description: "Modèle des produits avec leurs catégories, marques, prix, etc."
    columns:
      - name: id
        description: "Identifiant unique du produit"
        tests:
          - not_null
          - unique
          
      - name: Categorie
        description: "Catégorie du produit"
        tests:
          - not_null

      - name: marque
        description: "Marque du produit"
        tests:
          - not_null

      - name: produit
        description: "Nom du produit"
        tests:
          - not_null

      - name: prix
        description: "Prix du produit"
        tests:
          - not_null
          - accepted_values:
              values: [ "prix_min", "prix_max" ]  # Ajustez avec des valeurs spécifiques si nécessaire

      - name: sous-catégorie
        description: "Sous-catégorie du produit"
        tests:
          - not_null

      - name: variation
        description: "Variation du produit (ex: couleur, taille, etc.)"
        tests:
          - not_null
  - name: stg_promotions
    description: "Modèle des promotions contenant les informations relatives aux produits, types de promotions, et valeurs de promotions."
    columns:
      - name: id_promotion
        description: "Identifiant unique de la promotion"
        tests:
          - not_null
          - unique

      - name: id_produit
        description: "Identifiant du produit associé à la promotion"
        tests:
          - not_null

      - name: type_promotion
        description: "Type de la promotion (réduction, offre spéciale, etc.)"
        tests:
          - not_null

      - name: valeur_promotion
        description: "Valeur de la promotion (en pourcentage ou montant)"
        tests:
          - not_null

      - name: valeur_promotion_float
        description: "Valeur de la promotion après nettoyage et conversion en type FLOAT64 (nettoyée des virgules et des signes de pourcentage)"
        tests:
          - not_null
          - accepted_values:
              values: ["float"]  # La colonne attend une valeur numérique (type float)

      - name: date_début
        description: "Date de début de la promotion"
        tests:
          - not_null

      - name: date_fin
        description: "Date de fin de la promotion"
        tests:
          - not_null

      - name: responsable_promotion
        description: "Responsable de la gestion de la promotion"
        tests:
          - not_null
